{% set name = "mdit-py-plugins" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 06dbda99e7d81184c4f6de7c7e3409b29f5cef35404beed6feaf624646219bf5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - markdown-it-py >=0.5.8,<2.0.0
    - python >=3.6

test:
  imports:
    - mdit_py_plugins
    - mdit_py_plugins.amsmath
    - mdit_py_plugins.anchors
    - mdit_py_plugins.container
    - mdit_py_plugins.deflist
    - mdit_py_plugins.dollarmath
    - mdit_py_plugins.footnote
    - mdit_py_plugins.front_matter
    - mdit_py_plugins.myst_blocks
    - mdit_py_plugins.myst_role
    - mdit_py_plugins.tasklists
    - mdit_py_plugins.texmath

about:
  home: https://github.com/executablebooks/mdit-py-plugins
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Collection of plugins for markdown-it-py
  doc_url: https://markdown-it-py.readthedocs.io/en/latest/plugins.html

extra:
  recipe-maintainers:
    - chrisjsewell
